name: Deployment prerunner

on:
  pull_request:
    branches:
      - 'main'

jobs:
  scanner:
    runs-on: ubuntu-latest
    name: Vulnerability scan
    steps:
    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.12.0
  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      - name: Python package installer
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests.py