name: Deployment prerunner

on:
  pull_request:
    branches:
      - 'main'

jobs:
  scanner:
    runs-on: ubuntu-latest
    name: Vulnerability scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          cmd_options: '-a'
  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      - name: Python package installer
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests.py