name: Testing Workflow

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip
      - name: Python package installer
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests.py