name: Vulnerability Scanner

on:
  push:
    branches:
      - main

jobs:
  scanner:
    runs-on: ubuntu-latest
    name: Vulnerability scan
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.14.0
      with:
        target: 'https://tms-pidn.onrender.com/'